version: 0.0
os: linux
files:
  - source: /target/springboot-0.0.1-SNAPSHOT.war
    destination: /opt/tomcat/webapps/
hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
